services:
  nginx:
    container_name: wordpress-nginx
    build: ./nginx/
    image: wordpress-nginx-image
    ports:
      - '80:80'

  app:
    container_name: wordpress
    build: ./app/
    image: wordpress-app-image

  db:
    container_name: wordpress-db
    build: ./mysql/
    image: wordpress-db-image
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
